version: '3.8'
services:
  epadd-curator-app:
    container_name: "epadd-curator-app"
    build:
      context: "."
      dockerfile: "Dockerfile"
    env_file: .env
    volumes:
      - ./logs:/home/appuser/epadd-curator-app/logs
      - ./test/data/dropbox:/home/appuser/dropbox
    networks:
      - drsts-net

networks:
  drsts-net:
    name: "drsts-net"
